#версия парсера файла, влияет на доступность некоторых фич, более подробное описание на официальном сайта
version: "3.9"
#контейнеры, которые буду запускаться в docker-compose, их принято называть сервисами
services:
  #сервис базы данных, будем использовать mariadb
  mysql:
    image: mariadb:latest
    container_name: mariadb_aton
    restart: on-failure
    environment:
      #при необходимости при запуске конейтенра сразу будет создана база
      MYSQL_DATABASE: aton
      #при необходимости при запуске контейнера сразу будет создан допонительный пользователь
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      #рут пароль
      MYSQL_ROOT_PASSWORD: admin
    network_mode: "host"
    ports:
      - "3308:3306"
    #внешняя дериктория для сохранения данных
    volumes:
    #  - /opt/test/mariacnf:/etc/mysql/conf.d
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "-padmin"]
      interval: 1s
      timeout: 20s
      retries: 10
  javaindocer:
    container_name: javaindocker
    image: javaindocker:latest
    restart: on-failure
    #сборка образа javaindocker из докерфайла
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "8081:8080"
    environment:
      #переменная окружения в которую передаем память выделяему для процесса javaindocker
      JAVA_MAX_MEMORY: 256m
      #переменная окружения для обновления конфига адреса биндинга для javaindocker
      JAVAINDOCKER_HOST: "*"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: "netstat -an | grep 9014 > /dev/null; if [ 0 == $$? ]; then echo 1; fi;"
      interval: 1s
      timeout: 1s
      retries: 10
    #внешняя дериктория для сохранения данных
    volumes:
      - /var/logs:/server/logs
    profiles:
      - server