
spring:
  application:
    name: java-in-docker
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog.yaml
    parameters:
      spring.datasource.password: ${spring.datasource.password}
  datasource:
    generate-unique-name: false
    url: jdbc:mysql://localhost:3306/aton
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: default
    generate-ddl: false
    properties:
      connection:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: none
        show-sql: true
        format-sql: true
#  security:
#    user:
#      name: Alexander
#      password: mypassword
  messages:
    basename: messages
    encoding: UTF-8
  server:
    error:
      include-message: always
      include-binding-errors: always
      whitelabel:
        enabled: false

