

spring:
  application:
    name: java-in-docker
  datasource:
    generate-unique-name: false
    url: jdbc:mysql://localhost:3306/aton
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: file:/home/alexander/IdeaProjects/JavaInDocker/src/main/resources/mystatic/
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: default
    generate-ddl: false
    properties:
      connection:
        charSet: utf-8
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: none
        show_sql: true
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    validateOnMigrate: true
    url: jdbc:mysql://localhost:3306/aton
    user: admin
    password: admin
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/  #this is the main
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: my-group
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  #  security:
#    user:
#      name: Alexander
#      password: mypassword
  messages:
    basename: messages
    encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    throw-exception-if-no-handler-found: true
    throw-no-handler-found: true
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  cxf:
    path: /Service
  server:
    error:
      include-message: always
      include-binding-errors: always
      whitelabel:
        enabled: false