apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      initContainers:
        - name: wait-for-mysql
          image: mysql:8
          command:
            - sh
            - -c
            - |
              until mysqladmin ping -h mysql --silent; do
                echo "waiting for mysql..."
                sleep 2
              done
      containers:
        - name: myapp
          image: javaindocker:2.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/aton"
              #value: "jdbc:mysql://mysql.default.svc.cluster.local:3306/aton"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "rootpass"
            - name: SPRING_FLYWAY_ENABLED
              value: "true"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: SPRING_RABBITMQ_ADDRESSES
              value: "rabbitmq:5672"
            - name: SPRING_FLYWAY_URL
              value: "jdbc:mysql://mysql:3306/aton"
            - name: SPRING_FLYWAY_USER
              value: "root"
            - name: SPRING_FLYWAY_PASSWORD
              value: "rootpass"